-- Audit and optional cleanup for synthetic imported placeholder questions.
-- These rows were generated by the old PDF import pipeline and are not exact reviewer questions.

select
  count(*) as synthetic_placeholder_rows
from public.question_bank
where question ilike 'Based on imported reviewer%';

select
  id,
  category,
  sub_category,
  difficulty,
  question,
  status,
  source
from public.question_bank
where question ilike 'Based on imported reviewer%'
order by id
limit 25;

-- Uncomment only after confirming the audit result above.
-- delete from public.question_bank
-- where question ilike 'Based on imported reviewer%';
